/**
 * EZAUTH-BCRYPT-NATIVE-001 — sanity check that swapping bcryptjs for
 * @node-rs/bcrypt preserves the `$2a$` / `$2b$` hash format used by every
 * existing password and backup-code hash in production.
 *
 * If this test ever fails, NEW hashes generated by `@node-rs/bcrypt` would not
 * be verifiable by the next `compare()` call (or, worse, every legacy `$2a$`
 * hash already stored in Mongo would suddenly stop validating). Both would
 * lock every existing user out of their account on deploy — so we hard-pin
 * the contract here.
 */

import { describe, it, expect } from 'vitest'
import { compare, genSalt, hash } from '@node-rs/bcrypt'

describe('@node-rs/bcrypt backward-compat with legacy bcryptjs $2a$ hashes', () => {
  // DUMMY_BCRYPT_HASH constant from auth.service.ts (MED-2 anti-enumeration
  // dummy hash). Was generated by the legacy bcryptjs implementation — must
  // still verify with the native binding so the miss-path keeps working.
  const LEGACY_BCRYPTJS_HASH = '$2a$12$pCBbNeZtb//laRE6gKE0muioZJWbgAnaZgPzeeh7hFhlPlxbCgKnG'

  it('produces hashes in the $2 family (a/b/x/y) — never $2 missing', async () => {
    const salt = await genSalt(12)
    const fresh = await hash('hello-world', undefined, salt)
    expect(fresh.startsWith('$2')).toBe(true)
    // Cost factor 12 = the rounds we use everywhere (pre-save hook + setup).
    expect(fresh).toMatch(/^\$2[abxy]\$12\$/)
  })

  it('verifies a freshly-generated native hash with the matching plain', async () => {
    const salt = await genSalt(12)
    const fresh = await hash('CorrectHorseBatteryStaple9', undefined, salt)
    const ok = await compare('CorrectHorseBatteryStaple9', fresh)
    expect(ok).toBe(true)
  })

  it('rejects a wrong plain against a freshly-generated native hash', async () => {
    const salt = await genSalt(12)
    const fresh = await hash('CorrectHorseBatteryStaple9', undefined, salt)
    const ok = await compare('wrong-password', fresh)
    expect(ok).toBe(false)
  })

  it('verifies a LEGACY bcryptjs-shaped $2a$ hash (deploy-safety)', async () => {
    // The DUMMY hash above was generated by bcryptjs with rounds=12.
    // `compare()` must return `false` for a random password (the dummy hash
    // matches NO real account). We assert the call SUCCEEDS (returns a
    // boolean) rather than throwing — that's the deploy-safety guarantee.
    const result = await compare('anything-not-the-original-plain', LEGACY_BCRYPTJS_HASH)
    expect(result).toBe(false)
  })
})
