[phases.setup]
nixPkgs = ['nodejs', 'corepack']

[phases.install]
cmds = ['corepack enable', 'corepack prepare pnpm@latest --activate', 'pnpm install']

[phases.build]
cmds = ['pnpm --filter api build']

[start]
cmd = 'pnpm --filter api start'
