export { Tag } from './src/components/tag'
export type { TagProps } from './src/components/tag'
export type { TagAriaProps } from './src/types'
export { INTENT_ARIA_MAP } from './src/types'
export { tagVariants, tagVariantsKeys, tagVariantsMeta } from './src/variants'
export * from './src/variants/groups/heading'
export * from './src/variants/groups/listing'
export * from './src/variants/tags/aside'
export * from './src/variants/tags/div'
export * from './src/variants/tags/main'
export * from './src/variants/tags/nav'
export * from './src/variants/tags/p'
export * from './src/variants/tags/section'
export * from './src/variants/tags/span'

// Aliases (not covered by variant group exports)
export { Strong, Article, Ol } from './src/aliases'
