/**
 * Dynamic project configuration generator
 * Automatically generates PROJECT_ENDPOINTS from @ezstart/config
 */

import type { AppName } from '@ezstart/config'
import {
  getActiveApps,
  getProjectMetadata,
  hasApi,
  getApiUrl,
  getWebUrl,
  getGitHubUrl,
  getLogoUrl,
} from '@ezstart/config'
import type { ProjectId, ProjectConfig } from '../types/project.js'

/**
 * Default endpoint counts for APIs
 * Can be extended at runtime via registerEndpointCount()
 */
const DEFAULT_API_ENDPOINTS_COUNT: Partial<Record<string, number>> = {
  ezauth: 8,
  ezbill: 49,
  ezpay: 6,
  'green-pulse': 2,
}

let _apiEndpointsCounts: Partial<Record<string, number>> = { ...DEFAULT_API_ENDPOINTS_COUNT }

/**
 * Register endpoint count for an app at runtime
 */
export function registerEndpointCount(appName: string, count: number) {
  _apiEndpointsCounts = { ..._apiEndpointsCounts, [appName]: count }
}

/**
 * Get all registered endpoint counts
 */
export function getApiEndpointsCounts(): Partial<Record<string, number>> {
  return _apiEndpointsCounts
}

/**
 * Generate endpoints configuration for an app
 */
function generateEndpoints(app: AppName): ProjectConfig['endpoints'] {
  const metadata = getProjectMetadata(app)
  const endpoints: ProjectConfig['endpoints'] = []

  // Add API endpoint if app has one
  if (hasApi(app)) {
    // EZStart API has /api/health (custom monitoring route)
    // All other APIs have /health (auto-generated by express-core)
    const healthPath = app === 'ezstart' ? '/api/health' : '/health'

    endpoints.push({
      type: 'api',
      label: 'API',
      getUrl: env => {
        const apiUrl = getApiUrl(app, env)
        return `${apiUrl}${healthPath}`
      },
      platform: metadata.apiPlatform,
      endpointsCount: _apiEndpointsCounts[app],
      getSwaggerUrl: env => {
        const apiUrl = getApiUrl(app, env)
        return `${apiUrl}/docs`
      },
    })
  }

  // Add Web endpoint
  endpoints.push({
    type: 'web',
    label: 'Web',
    getUrl: env => getWebUrl(app, env),
    platform: metadata.webPlatform,
  })

  return endpoints
}

/**
 * Generate complete project configuration from @ezstart/config
 * Only includes active projects (excludes paused/archived)
 */
export function generateProjectConfig(): Record<ProjectId, ProjectConfig> {
  const activeApps = getActiveApps()
  const config: Partial<Record<ProjectId, ProjectConfig>> = {}

  for (const app of activeApps) {
    const metadata = getProjectMetadata(app)
    const logoUrl = getLogoUrl(app)

    config[app as ProjectId] = {
      name: metadata.name,
      emoji: metadata.emoji,
      logo: logoUrl,
      description: metadata.description,
      githubUrl: getGitHubUrl(app),
      endpoints: generateEndpoints(app),
    }
  }

  return config as Record<ProjectId, ProjectConfig>
}

/**
 * Get dynamically generated PROJECT_ENDPOINTS
 * This replaces the hardcoded configuration
 */
export const PROJECT_ENDPOINTS = generateProjectConfig()
