/**
 * Types for health check system
 */

import { URLS } from '@ezstart/config'

export type ServiceType = 'api' | 'web' | 'database' | 'external'

export type HealthStatus = 'healthy' | 'degraded' | 'unhealthy' | 'unknown'

export interface HealthCheckConfig {
  name: string
  type: ServiceType
  url: string
  timeout: number // ms
  interval: number // ms
  retries: number
  expectedStatus?: number
  headers?: Record<string, string>
}

export interface HealthCheckResult {
  name: string
  type: ServiceType
  status: HealthStatus
  responseTime: number | null // ms
  timestamp: Date
  error: string | null
  metadata?: Record<string, unknown>
}

export interface ServiceHealth {
  service: string
  type: ServiceType
  status: HealthStatus
  uptime: number // percentage
  avgResponseTime: number // ms
  lastCheck: Date
  lastHealthy: Date | null
  lastUnhealthy: Date | null
  checks: HealthCheckResult[]
}

/**
 * Adaptive Health Check Configuration
 * Implements exponential backoff for efficient monitoring
 */
export interface AdaptiveCheckState {
  serviceId: MonitoredServiceId
  consecutiveSuccesses: number
  consecutiveFailures: number
  currentInterval: number // Current interval in ms
  nextCheckAt: Date
  lastStatus: HealthStatus
}

/**
 * Exponential Backoff Configuration
 *
 * Strategy:
 * - Service UP → Increase interval progressively (save resources)
 * - Service DOWN → Reset to minimum interval (fast recovery detection)
 *
 * Example progression:
 * ✅ Check 1: UP → Next in 5 min (base)
 * ✅ Check 2: UP → Next in 10 min (2x)
 * ✅ Check 3: UP → Next in 20 min (2x)
 * ✅ Check 4: UP → Next in 40 min (2x)
 * ✅ Check 5: UP → Next in 60 min (max, capped)
 * ❌ Check 6: DOWN → Next in 5 min (reset!)
 */
export const ADAPTIVE_CHECK_CONFIG = {
  // Minimum interval (after failure or initial check)
  MIN_INTERVAL_MS: 5 * 60 * 1000, // 5 minutes

  // Maximum interval (for stable services)
  MAX_INTERVAL_MS: 60 * 60 * 1000, // 60 minutes

  // Multiplier for exponential backoff
  BACKOFF_MULTIPLIER: 2,

  // Number of consecutive successes needed before increasing interval
  SUCCESS_THRESHOLD: 1,

  // Number of consecutive failures before alerting
  FAILURE_THRESHOLD: 3,

  // Render-specific: Maximum interval to keep services awake (sleep after 15min)
  RENDER_MAX_INTERVAL_MS: 10 * 60 * 1000, // 10 minutes (safe margin)
} as const

/**
 * Shape of a monitored service entry
 */
export interface MonitoredService {
  name: string
  type: ServiceType
  localUrl: string
  productionUrl: string
  port: string
}

/**
 * Default monitored services - Auto-generated from @ezstart/config
 * Single source of truth for all service URLs and ports
 */
const DEFAULT_MONITORED_SERVICES = {
  // APIs - Standard /health endpoint (auto-generated by express-core)
  // Only ezstart-api has /api/health (custom monitoring route)
  'ezauth-api': {
    name: 'EZAuth API',
    type: 'api' as ServiceType,
    localUrl: `${URLS.ezauth.api?.local}/health`,
    productionUrl: `${URLS.ezauth.api?.production}/health`,
    port: new URL(URLS.ezauth.api!.local).port,
  },
  'ezpay-api': {
    name: 'EZPay API',
    type: 'api' as ServiceType,
    localUrl: `${URLS.ezpay.api?.local}/health`,
    productionUrl: `${URLS.ezpay.api?.production}/health`,
    port: new URL(URLS.ezpay.api!.local).port,
  },
  'ezbill-api': {
    name: 'EZBill API',
    type: 'api' as ServiceType,
    localUrl: `${URLS.ezbill.api?.local}/health`,
    productionUrl: `${URLS.ezbill.api?.production}/health`,
    port: new URL(URLS.ezbill.api!.local).port,
  },
  'green-pulse-api': {
    name: 'GreenPulse API',
    type: 'api' as ServiceType,
    localUrl: `${URLS['green-pulse'].api?.local}/health`,
    productionUrl: `${URLS['green-pulse'].api?.production}/health`,
    port: new URL(URLS['green-pulse'].api!.local).port,
  },
  'ezstart-api': {
    name: 'EZStart API (Monitoring)',
    type: 'api' as ServiceType,
    localUrl: `${URLS.ezstart.api?.local}/api/health`,
    productionUrl: `${URLS.ezstart.api?.production}/api/health`,
    port: new URL(URLS.ezstart.api!.local).port,
  },

  // Web Apps - Root URL health check
  'ezstart-web': {
    name: 'EZStart',
    type: 'web' as ServiceType,
    localUrl: URLS.ezstart.web.local,
    productionUrl: URLS.ezstart.web.production,
    port: new URL(URLS.ezstart.web.local).port,
  },
  'ezauth-web': {
    name: 'EZAuth',
    type: 'web' as ServiceType,
    localUrl: URLS.ezauth.web.local,
    productionUrl: URLS.ezauth.web.production,
    port: new URL(URLS.ezauth.web.local).port,
  },
  'ezbill-web': {
    name: 'EZBill',
    type: 'web' as ServiceType,
    localUrl: URLS.ezbill.web.local,
    productionUrl: URLS.ezbill.web.production,
    port: new URL(URLS.ezbill.web.local).port,
  },
  'ezpay-web': {
    name: 'EZPay',
    type: 'web' as ServiceType,
    localUrl: URLS.ezpay.web.local,
    productionUrl: URLS.ezpay.web.production,
    port: new URL(URLS.ezpay.web.local).port,
  },
  'fengshui-web': {
    name: 'FengShui',
    type: 'web' as ServiceType,
    localUrl: URLS.fengshui.web.local,
    productionUrl: URLS.fengshui.web.production,
    port: new URL(URLS.fengshui.web.local).port,
  },
  'asc-tcd-web': {
    name: 'ASC-TCD',
    type: 'web' as ServiceType,
    localUrl: URLS['asc-tcd'].web.local,
    productionUrl: URLS['asc-tcd'].web.production,
    port: new URL(URLS['asc-tcd'].web.local).port,
  },
  'green-pulse-web': {
    name: 'GreenPulse',
    type: 'web' as ServiceType,
    localUrl: URLS['green-pulse'].web.local,
    productionUrl: URLS['green-pulse'].web.production,
    port: new URL(URLS['green-pulse'].web.local).port,
  },
} satisfies Record<string, MonitoredService>

/**
 * Backward-compatible constant with known keys.
 * Use getMonitoredServices() when you need runtime-registered services too.
 */
export const MONITORED_SERVICES = DEFAULT_MONITORED_SERVICES

export type MonitoredServiceId = keyof typeof DEFAULT_MONITORED_SERVICES

/** Mutable registry — starts with defaults, extended via registerService() */
let _registeredServices: Record<string, MonitoredService> = {}

/**
 * Register a new service for monitoring at runtime.
 * Keeps backward compatibility: existing code still works without calling this.
 */
export function registerService(id: string, config: MonitoredService) {
  _registeredServices = { ..._registeredServices, [id]: config }
}

/**
 * Get all monitored services (defaults + runtime-registered)
 */
export function getMonitoredServices(): Record<string, MonitoredService> {
  return { ...DEFAULT_MONITORED_SERVICES, ..._registeredServices }
}

/**
 * Platform configuration for health checks
 */
export const SERVICE_PLATFORMS = {
  // Railway ($5/month Hobby Plan) - All APIs deployed, adaptive interval to save bandwidth
  railway: [
    'ezstart-api',
    'ezauth-api',
    'ezpay-api',
    'ezbill-api',
    'green-pulse-api',
  ] as MonitoredServiceId[],

  // Render (free) - No longer used (migrated to Railway)
  render: [] as MonitoredServiceId[],

  // Vercel (free) - Web apps, adaptive interval (they don't sleep)
  vercel: [
    'ezstart-web',
    'ezauth-web',
    'ezbill-web',
    'ezpay-web',
    'fengshui-web',
    'asc-tcd-web',
    'green-pulse-web',
  ] as MonitoredServiceId[],
} as const

/**
 * Get URLs to check based on environment
 * - Development: Check ONLY local URLs (don't consume production resources)
 * - Production: Check ALL production URLs (Railway for monitoring, Render to prevent sleep, Vercel for uptime)
 */
export function getUrlsToCheck(
  serviceId: MonitoredServiceId | string,
  environment: 'development' | 'production' = 'development'
): Array<{ url: string; label: string }> {
  const services = getMonitoredServices()
  const config = services[serviceId]
  if (!config) {
    throw new Error(`[monitoring] Unknown service: ${serviceId}`)
  }

  if (environment === 'production') {
    // Production: Check all services (Railway + Render + Vercel)
    return [{ url: config.productionUrl, label: 'production' }]
  }

  // Development: Only check local URLs
  return [{ url: config.localUrl, label: 'local' }]
}

/**
 * Get maximum interval for a service based on platform
 * Render services must be checked more frequently to prevent sleep
 */
export function getMaxIntervalForService(serviceId: MonitoredServiceId | string): number {
  if ((SERVICE_PLATFORMS.render as readonly string[]).includes(serviceId)) {
    return ADAPTIVE_CHECK_CONFIG.RENDER_MAX_INTERVAL_MS
  }
  return ADAPTIVE_CHECK_CONFIG.MAX_INTERVAL_MS
}

/**
 * Calculate next check interval using exponential backoff
 *
 * @param state Current adaptive check state
 * @returns Next interval in milliseconds
 */
export function calculateNextInterval(state: AdaptiveCheckState): number {
  const { currentInterval, consecutiveSuccesses, lastStatus } = state
  const maxInterval = getMaxIntervalForService(state.serviceId)

  // If last check failed, reset to minimum
  if (lastStatus !== 'healthy') {
    return ADAPTIVE_CHECK_CONFIG.MIN_INTERVAL_MS
  }

  // If not enough consecutive successes, keep current interval
  if (consecutiveSuccesses < ADAPTIVE_CHECK_CONFIG.SUCCESS_THRESHOLD) {
    return currentInterval
  }

  // Increase interval exponentially, but cap at max
  const nextInterval = Math.min(
    currentInterval * ADAPTIVE_CHECK_CONFIG.BACKOFF_MULTIPLIER,
    maxInterval
  )

  return nextInterval
}
