/**
 * Entity Types - Shared definitions for Mobs and Towers
 *
 * Single source of truth used by both:
 * - Backend (API): EntityRegistry seeding
 * - Frontend (Web): TowerShop and MobShop displays
 *
 * This ensures type safety and consistency across the entire game.
 */

import type { MobType, TowerType } from '@tower-defense/types'

/**
 * Mob Types - 15 varied mobs across all elements
 * Balanced progression from basic to advanced
 */
export const ENTITY_MOB_TYPES: MobType[] = [
  // === NORMAL (Basic) ===
  {
    _id: 'mob-basic-slime',
    name: 'Basic Slime',
    elementalType: 'normal',
    hp: 30,
    speed: 5,
    damage: 1,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.3,
  },
  {
    _id: 'mob-armored-knight',
    name: 'Armored Knight',
    elementalType: 'normal',
    hp: 80,
    speed: 3,
    damage: 2,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.4,
  },
  {
    _id: 'mob-flying-bat',
    name: 'Flying Bat',
    elementalType: 'normal',
    hp: 20,
    speed: 7,
    damage: 1,
    canFly: true, // Ignores collisions
    attackRange: 0,
    collisionRadius: 0.2,
  },

  // === FIRE ===
  {
    _id: 'mob-fire-imp',
    name: 'Fire Imp',
    elementalType: 'fire',
    hp: 25,
    speed: 6,
    damage: 2,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.3,
  },
  {
    _id: 'mob-lava-golem',
    name: 'Lava Golem',
    elementalType: 'fire',
    hp: 100,
    speed: 2,
    damage: 3,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.5,
  },
  {
    _id: 'mob-phoenix',
    name: 'Phoenix',
    elementalType: 'fire',
    hp: 40,
    speed: 8,
    damage: 2,
    canFly: true,
    attackRange: 2, // Ranged attacker
    collisionRadius: 0.3,
  },

  // === WATER ===
  {
    _id: 'mob-water-sprite',
    name: 'Water Sprite',
    elementalType: 'water',
    hp: 35,
    speed: 5,
    damage: 1,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.3,
  },
  {
    _id: 'mob-ice-giant',
    name: 'Ice Giant',
    elementalType: 'water',
    hp: 90,
    speed: 3,
    damage: 2,
    effects: ['slow'],
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.5,
  },
  {
    _id: 'mob-frost-dragon',
    name: 'Frost Dragon',
    elementalType: 'water',
    hp: 70,
    speed: 6,
    damage: 3,
    effects: ['slow'],
    canFly: true,
    attackRange: 3,
    collisionRadius: 0.4,
  },

  // === GRASS ===
  {
    _id: 'mob-vine-walker',
    name: 'Vine Walker',
    elementalType: 'grass',
    hp: 40,
    speed: 4,
    damage: 1,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.3,
  },
  {
    _id: 'mob-treant',
    name: 'Treant',
    elementalType: 'grass',
    hp: 85,
    speed: 2,
    damage: 2,
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.5,
  },
  {
    _id: 'mob-poison-bee',
    name: 'Poison Bee',
    elementalType: 'grass',
    hp: 15,
    speed: 9,
    damage: 1,
    canFly: true,
    attackRange: 1,
    collisionRadius: 0.2,
  },

  // === ELECTRIC ===
  {
    _id: 'mob-spark-wisp',
    name: 'Spark Wisp',
    elementalType: 'electric',
    hp: 25,
    speed: 7,
    damage: 2,
    effects: ['stun'],
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.2,
  },
  {
    _id: 'mob-thunder-titan',
    name: 'Thunder Titan',
    elementalType: 'electric',
    hp: 95,
    speed: 4,
    damage: 3,
    effects: ['stun'],
    canFly: false,
    attackRange: 0,
    collisionRadius: 0.5,
  },
  {
    _id: 'mob-lightning-hawk',
    name: 'Lightning Hawk',
    elementalType: 'electric',
    hp: 30,
    speed: 10,
    damage: 2,
    effects: ['stun'],
    canFly: true,
    attackRange: 2,
    collisionRadius: 0.3,
  },
]

/**
 * Tower Types - 15 varied towers across all elements and strategies
 * Balanced mix of single-target, splash, and special effects
 */
export const ENTITY_TOWER_TYPES: TowerType[] = [
  // === NORMAL (Basic) ===
  {
    _id: 'tower-basic-archer',
    name: 'Archer Tower',
    elementalType: 'normal',
    damage: 2,
    damageType: 'single',
    speed: 1,
    range: 5,
    shape: [[true]],
    targetingStrategy: 'first',
    description: 'Basic single-target tower',
  },
  {
    _id: 'tower-sniper',
    name: 'Sniper Tower',
    elementalType: 'normal',
    damage: 5,
    damageType: 'single',
    speed: 0.5, // Slow but powerful
    range: 8,
    shape: [[true]],
    targetingStrategy: 'last',
    description: 'Long range, high damage, slow attack',
  },
  {
    _id: 'tower-cannon',
    name: 'Cannon Tower',
    elementalType: 'normal',
    damage: 3,
    damageType: 'splash',
    speed: 0.7,
    range: 6,
    shape: [[true]],
    splashRadius: 2,
    targetingStrategy: 'strongest',
    description: 'Area of effect damage',
  },

  // === FIRE ===
  {
    _id: 'tower-fire-basic',
    name: 'Flame Thrower',
    elementalType: 'fire',
    damage: 2,
    damageType: 'single',
    speed: 1.5, // Fast attacks
    range: 4,
    shape: [[true]],
    effect: 'burn',
    targetingStrategy: 'first',
    description: 'Burns enemies over time',
  },
  {
    _id: 'tower-inferno',
    name: 'Inferno Tower',
    elementalType: 'fire',
    damage: 4,
    damageType: 'splash',
    speed: 1,
    range: 5,
    shape: [[true]],
    splashRadius: 2.5,
    effect: 'burn',
    targetingStrategy: 'closest',
    description: 'Massive fire AoE',
  },
  {
    _id: 'tower-fire-dual',
    name: 'Phoenix Nest',
    elementalType: ['fire', 'normal'],
    damage: 3,
    damageType: 'single',
    speed: 1.2,
    range: 6,
    shape: [[true, true]],
    effect: 'burn',
    targetingStrategy: 'first',
    description: 'Dual-type fire tower',
  },

  // === WATER ===
  {
    _id: 'tower-water-basic',
    name: 'Ice Shard',
    elementalType: 'water',
    damage: 2,
    damageType: 'single',
    speed: 1,
    range: 5,
    shape: [[true]],
    effect: 'slow',
    targetingStrategy: 'first',
    description: 'Slows enemies',
  },
  {
    _id: 'tower-blizzard',
    name: 'Blizzard Tower',
    elementalType: 'water',
    damage: 2,
    damageType: 'splash',
    speed: 1.5,
    range: 6,
    shape: [[true]],
    splashRadius: 3,
    effect: 'slow',
    targetingStrategy: 'closest',
    description: 'Slows multiple enemies',
  },
  {
    _id: 'tower-water-dual',
    name: 'Tidal Wave',
    elementalType: ['water', 'grass'],
    damage: 3,
    damageType: 'splash',
    speed: 0.8,
    range: 5,
    shape: [[true], [true]],
    splashRadius: 2,
    effect: 'slow',
    targetingStrategy: 'strongest',
    description: 'Water-grass hybrid tower',
  },

  // === GRASS ===
  {
    _id: 'tower-grass-basic',
    name: 'Vine Snare',
    elementalType: 'grass',
    damage: 1,
    damageType: 'single',
    speed: 2, // Very fast
    range: 4,
    shape: [[true]],
    effect: 'slow',
    targetingStrategy: 'first',
    description: 'Fast slowing attacks',
  },
  {
    _id: 'tower-nature-guardian',
    name: 'Nature Guardian',
    elementalType: 'grass',
    damage: 3,
    damageType: 'single',
    speed: 1,
    range: 5,
    shape: [[true, true], [true, true]],
    targetingStrategy: 'first',
    description: 'Large 2x2 defensive tower',
  },
  {
    _id: 'tower-grass-dual',
    name: 'Overgrowth',
    elementalType: ['grass', 'electric'],
    damage: 2,
    damageType: 'splash',
    speed: 1.3,
    range: 5,
    shape: [[true]],
    splashRadius: 1.5,
    effect: 'slow',
    targetingStrategy: 'closest',
    description: 'Grass-electric hybrid',
  },

  // === ELECTRIC ===
  {
    _id: 'tower-electric-basic',
    name: 'Tesla Coil',
    elementalType: 'electric',
    damage: 2,
    damageType: 'single',
    speed: 1.5,
    range: 5,
    shape: [[true]],
    effect: 'stun',
    targetingStrategy: 'first',
    description: 'Stuns fast enemies',
  },
  {
    _id: 'tower-lightning-storm',
    name: 'Lightning Storm',
    elementalType: 'electric',
    damage: 4,
    damageType: 'splash',
    speed: 0.9,
    range: 6,
    shape: [[true]],
    splashRadius: 2.5,
    effect: 'stun',
    targetingStrategy: 'strongest',
    description: 'Chain lightning effect',
  },
  {
    _id: 'tower-electric-dual',
    name: 'Thunderforge',
    elementalType: ['electric', 'fire'],
    damage: 4,
    damageType: 'single',
    speed: 1,
    range: 7,
    shape: [[true, true, true]],
    effect: 'stun',
    targetingStrategy: 'strongest',
    description: 'Powerful electric-fire combo',
  },
]
