/**
 * Enhanced SEO Configuration for GreenPulse
 *
 * AI-powered dynamic form builder with natural language generation.
 * Data extracted from docs/seo/ALL-APPS-SUMMARY.md
 */

import type { AppSEOConfig } from './ezstart'

export const greenPulseSEO: AppSEOConfig = {
  appName: 'GreenPulse',
  tagline: 'AI Form Builder - Describe It, Get It',
  shortDescription: 'Generate complex forms from natural language prompts with AI assistance.',
  longDescription: `GreenPulse is an AI-powered form builder that eliminates the tedious work of form creation. Instead of dragging-and-dropping fields for hours, simply describe what you need in natural language and AI generates a complete, working form instantly. "Create an employee onboarding form with personal details, emergency contact, and tax information" becomes a fully-functional multi-step wizard in seconds. Built for product managers prototyping UIs, developers building admin panels, researchers collecting data, and HR teams creating applications, GreenPulse handles the complexity: AI understands your requirements and generates appropriate fields, real-time validation on client and server side, multi-step wizards for complex flows automatically structured, conditional logic showing/hiding fields based on answers, and support for all field types (text, select, date, file upload, etc.). Unlike traditional form builders that require manual configuration of every field, GreenPulse uses AI to understand context and generate smart defaults. Need a phone number field? It adds format validation automatically. Need a date picker? It configures min/max dates intelligently. The result is production-ready forms in seconds instead of hours. Forms are fully customizable after generation - AI gives you 80% instantly, customize the final 20% if needed. Export as React components or use the API for dynamic form generation. TypeScript throughout means type-safe form handling and validation.`,

  mission: {
    what: 'AI-powered form builder that generates forms from natural language prompts.',
    why: 'Building forms is tedious, repetitive work that takes hours away from actual product development.',
    how: 'Use AI to understand requirements and generate complete forms instantly.',
  },

  features: [
    {
      title: 'AI Generation - Describe Form, Get Instant Result',
      description: 'Natural language input generates complete forms with validation',
      longDescription: 'Simply describe what you need: "Create a customer feedback survey with rating scale, multiple choice questions, and open text feedback." AI analyzes your prompt, identifies required fields, determines appropriate input types, configures validation rules, structures multi-step flow if needed, and generates working form code instantly. The AI understands context: "contact form" includes name, email, phone with proper validation. "Registration form" includes password with strength requirements. "Survey" includes rating scales and choice options. You get 80% of the form perfect immediately, then customize the remaining 20% if needed.',
      icon: 'lucide:Sparkles',
      keywords: ['ai form builder', 'form generator ai', 'natural language forms', 'ai form creation', 'smart form builder'],
      useCases: [
        'Product managers creating prototype forms for user research',
        'Developers building admin panels with complex data entry',
        'HR teams creating application and onboarding forms',
      ],
    },
    {
      title: 'Real-Time Validation - Client & Server Side',
      description: 'Comprehensive validation with instant feedback to users',
      longDescription: 'Forms generated by AI include intelligent validation: client-side validation for instant user feedback (check email format, required fields, min/max values), server-side validation for security (sanitize inputs, verify constraints, check business rules), and custom validation rules (unique email addresses, password strength, conditional requirements). Users see helpful error messages immediately, preventing frustration. Form submissions are validated before sending, reducing server load. TypeScript types ensure validation rules are enforced across frontend and backend.',
      icon: 'lucide:CheckCircle',
      keywords: ['form validation', 'real-time validation', 'client side validation', 'server validation', 'form error handling'],
      useCases: [
        'Registration forms with complex password requirements',
        'Data collection ensuring quality and completeness',
        'Applications preventing invalid submissions',
      ],
    },
    {
      title: 'Multi-Step Wizards - Complex Flows Made Easy',
      description: 'AI automatically structures long forms into logical steps',
      longDescription: 'Long forms are overwhelming. GreenPulse\'s AI automatically breaks complex forms into logical multi-step wizards: analyzes form fields and groups related information (personal info → contact details → preferences → review), creates progress indicators showing current step, handles navigation (next, back, skip optional steps), validates each step before proceeding, and provides summary/review before final submission. Users experience guided flow instead of overwhelming single-page form. Completion rates increase dramatically with well-structured wizards. AI determines optimal step count (too few = overwhelming, too many = tedious).',
      icon: 'lucide:GitBranch',
      keywords: ['multi-step form', 'form wizard', 'stepped form', 'form flow', 'progressive form'],
      useCases: [
        'Employee onboarding with 50+ fields across categories',
        'Complex applications requiring review before submission',
        'Surveys guiding users through different question types',
      ],
    },
  ],

  targetAudience: [
    {
      persona: 'Product Managers Needing Quick Prototypes',
      painPoints: [
        'Need form prototypes for user testing',
        'Don\'t code - can\'t build quickly',
        'Drag-and-drop builders too slow',
        'Requirements change constantly',
      ],
      goals: [
        'Generate forms in minutes for testing',
        'Iterate quickly based on feedback',
        'Professional-looking forms without design skills',
        'Focus on user research, not form building',
      ],
      characteristics: [
        'Non-technical or semi-technical',
        'Rapid prototyping workflows',
        'User-centered design focus',
        'Need speed and flexibility',
      ],
    },
    {
      persona: 'Developers Building Admin Panels',
      painPoints: [
        'Spend hours building CRUD forms',
        'Repetitive work for each model',
        'Form validation is tedious',
        'Many fields with complex requirements',
      ],
      goals: [
        'Generate admin forms automatically',
        'Focus on business logic, not forms',
        'Type-safe form handling',
        'Customizable when needed',
      ],
      characteristics: [
        'Full-stack developers',
        'Building internal tools',
        'Value automation and DRY principles',
        'TypeScript users',
      ],
    },
    {
      persona: 'Researchers Collecting Data',
      painPoints: [
        'Need surveys and questionnaires',
        'Forms must be accessible and clear',
        'Data quality is critical',
        'Limited budget for form tools',
      ],
      goals: [
        'Create professional surveys quickly',
        'Ensure data validity with validation',
        'Export data for analysis',
        'Cost-effective solution',
      ],
      characteristics: [
        'Academic or market researchers',
        'Need reliable data collection',
        'Focus on question quality',
        'Appreciate accessibility',
      ],
    },
  ],

  useCases: [
    {
      title: 'Product Manager: Prototype in 30 Seconds',
      before: 'Spent 2 days building a 20-field application form with validation. Manual drag-and-drop of every field. Configuring validation rules one by one. Finally done, stakeholders wanted changes.',
      after: 'Told AI: "Create application form with personal info, work history, and references." Had working form in 30 seconds. Stakeholders reviewed, requested changes, regenerated in 10 seconds.',
      metrics: {
        timelineBefore: '2 days',
        timelineAfter: '30 seconds',
      },
    },
    {
      title: 'Developer: Admin Panel in Minutes',
      before: 'Building admin panel for e-commerce. Needed forms for products (15 fields), categories (8 fields), users (12 fields). Spent 2 days coding forms, validation, error handling.',
      after: 'Used GreenPulse AI to generate all three forms. Customized styling and business rules. Admin panel done in 2 hours instead of 2 days. More time for actual features.',
      metrics: {
        timelineBefore: '2 days',
        timelineAfter: '2 hours',
      },
    },
  ],

  keywords: {
    primary: [
      { term: 'ai form builder', volume: 1600 },
      { term: 'form builder', volume: 14800 },
      { term: 'dynamic forms', volume: 880 },
      { term: 'survey tool', volume: 2900 },
      { term: 'form generator', volume: 1200 },
    ],
    secondary: [
      { term: 'online form creator', volume: 720 },
      { term: 'form builder ai', volume: 590 },
      { term: 'multi-step form builder', volume: 320 },
      { term: 'survey maker', volume: 480 },
      { term: 'ai survey generator', volume: 210 },
    ],
    longTail: [
      { term: 'ai powered form builder', volume: 170 },
      { term: 'generate forms from text', volume: 90 },
      { term: 'natural language form creator', volume: 50 },
      { term: 'automatic form generation', volume: 70 },
      { term: 'smart form builder with validation', volume: 40 },
    ],
  },

  usps: {
    title: 'The Only Form Builder Where AI Does the Work',
    description: 'Describe what you want, get a working form in seconds',
    differentiators: [
      'AI-Powered: Natural language → Complete form in seconds',
      'Smart Defaults: AI understands context and adds intelligent validation',
      'Multi-Step Wizards: Complex forms structured automatically',
      'Real-Time Validation: Client & server side built-in',
      'Export as Code: React components or API integration',
      'Fully Customizable: AI gives you 80%, customize 20%',
      'Type-Safe: TypeScript throughout for reliability',
      'Open Source: Own the code, no vendor lock-in',
    ],
  },

  vsCompetition: [
    {
      category: 'VS Traditional Form Builders (Typeform, Google Forms)',
      competitors: ['Typeform ($25-83/mo)', 'Google Forms (limited)', 'JotForm ($34-99/mo)'],
      ourAdvantage: 'They require manual field-by-field configuration. We use AI - describe what you need, get instant form. They charge $25-99/month. We\'re open-source and free. Plus, export as React components for integration.',
    },
    {
      category: 'VS Code-Based Form Libraries',
      competitors: ['React Hook Form', 'Formik', 'React Final Form'],
      ourAdvantage: 'Libraries require coding every field manually. GreenPulse generates 80% with AI, you customize 20%. Validation, multi-step logic, error handling - all automatic. Library gives you tools, we give you results.',
    },
  ],

  visualAssets: [
    {
      type: 'video',
      title: 'AI Form Generation Demo',
      description: 'Type prompt → AI generates form → Working in 30 seconds',
      specs: {
        duration: '45 seconds',
        resolution: '1920×1080',
        format: 'MP4',
        size: '<8MB',
      },
    },
    {
      type: 'gif',
      title: 'Form Generation',
      description: 'Natural language prompt becoming form',
      specs: {
        duration: '8 seconds loop',
        resolution: '1200×800',
        format: 'GIF',
        size: '<2MB',
      },
    },
    {
      type: 'screenshot',
      title: 'Multi-Step Wizard',
      description: 'Complex form broken into logical steps',
      specs: {
        resolution: '1400×900',
        format: 'WebP',
      },
    },
  ],

  callToAction: {
    primary: 'Generate Your First Form',
    secondary: 'Try AI Demo',
    url: 'https://greenpulse.ezstart.xyz',
  },

  socialProof: {
    stats: [
      { label: 'Generation Time', value: '<30 sec' },
      { label: 'Field Types Supported', value: '15+' },
      { label: 'Validation Rules', value: 'Auto' },
      { label: 'Monthly Cost', value: '$0' },
    ],
  },

  faq: [
    {
      question: 'How does the AI understand what form I need?',
      answer: 'The AI analyzes your natural language description, identifies required fields, determines appropriate input types, and configures validation rules based on context. For example, "contact form" automatically includes email validation.',
    },
    {
      question: 'Can I customize the generated form?',
      answer: 'Yes! AI gives you 80% instantly. You can customize fields, validation rules, styling, and logic. Forms are generated as React components you can modify.',
    },
    {
      question: 'Does it support multi-step forms?',
      answer: 'Yes, AI automatically structures long forms into logical multi-step wizards with progress indicators, navigation, and per-step validation.',
    },
    {
      question: 'How do I integrate generated forms into my app?',
      answer: 'Forms export as React components with TypeScript types. Copy the code into your project or use the API for dynamic generation. Includes validation and submission handling.',
    },
    {
      question: 'Is the form validation secure?',
      answer: 'Yes, both client-side (instant feedback) and server-side (security) validation are included. Never trust client-side only - server validation ensures data integrity.',
    },
  ],

  brandVoice: {
    tone: [
      'Modern and AI-forward',
      'Time-saving focused',
      'Practical and results-oriented',
      'Excited about automation',
    ],
    avoid: [
      'Overhyping AI capabilities',
      'Claiming 100% perfect generation',
      'Dismissing manual form building entirely',
      'Ignoring customization needs',
    ],
  },
}

export default greenPulseSEO
