export { Footer } from './footer'
export { MobileNavbar } from './mobile-navbar'
export { MobileNavMenu } from './mobile-nav-menu'
export { ClientLayout, type ClientLayoutProps, type BottomNavItem, type SocialLink, type FooterLink } from './client-layout'
export type { NavigationItem } from './client-layout'